### PR TITLE
Extension allowing the use of a different certstream server

### PR DESCRIPTION
**Pull request by nitram22**
Hi there,

I have added a few methods to allow users to use this library with another / their own certstream server instead of always having to access the default server "certstream.calidog.io".

Thank you for providing this project! Looking forward to your response.

### CODE REVIEW

**Comment by joshbooks** [comment]
@nitram22 I love the code contribution, but can I ask about use case?

**Comment by nitram22** [comment]
Thanks for your reply !

The library only allows to connect to the calidog certstream server.  But in general there might be people who want to use the with their own certstream server by hosting it themselves.

I am currently writing my thesis in the field of CT monitoring and my organization would like to host its own certstream server, for instance, but the library has not yet included a function that allows a connection to a server other than the default server. 

So I thought that my extension could be useful for people who want to host their own certstream server independently from the existing CaliDog certstream server and want to use your library to connect to it.

**Review by joshbooks — APPROVED** [review]
That’s awesome! I’m so psyched to hear you and your organization are so gung ho about using certstream and I wish you the best of luck with your thesis. Your replumbing all looks good, and refactoring the runThread method is an excellent example of clarifying intent with a function name.

**Comment by joshbooks** [comment]
@nitram22 cut release 0.3.2 with your changes

**Comment by nitram22** [comment]
Thank you very much ! 

And thanks a lot for providing this great project ! It facilitates the work of everyone who wants to create a CT-Monitor.

**Pull request merged**
